# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\"\x17\n\x07reqName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x15\n\x06resObj\x12\x0b\n\x03obj\x18\x01 \x01(\t2,\n\x07Message\x12!\n\nFindPlayer\x12\x08.reqName\x1a\x07.resObj\"\x00\x62\x06proto3'
)




_REQNAME = _descriptor.Descriptor(
  name='reqName',
  full_name='reqName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='reqName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=40,
)


_RESOBJ = _descriptor.Descriptor(
  name='resObj',
  full_name='resObj',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='obj', full_name='resObj.obj', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['reqName'] = _REQNAME
DESCRIPTOR.message_types_by_name['resObj'] = _RESOBJ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

reqName = _reflection.GeneratedProtocolMessageType('reqName', (_message.Message,), {
  'DESCRIPTOR' : _REQNAME,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:reqName)
  })
_sym_db.RegisterMessage(reqName)

resObj = _reflection.GeneratedProtocolMessageType('resObj', (_message.Message,), {
  'DESCRIPTOR' : _RESOBJ,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:resObj)
  })
_sym_db.RegisterMessage(resObj)



_MESSAGE = _descriptor.ServiceDescriptor(
  name='Message',
  full_name='Message',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=65,
  serialized_end=109,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindPlayer',
    full_name='Message.FindPlayer',
    index=0,
    containing_service=None,
    input_type=_REQNAME,
    output_type=_RESOBJ,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGE)

DESCRIPTOR.services_by_name['Message'] = _MESSAGE

# @@protoc_insertion_point(module_scope)
